spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    password: root
    url: jdbc:mysql://localhost:3306/inu_phonebook?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true

    username: root
    hikari:
      data-source-properties:
        socketTimeout: 30000
=======
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://{MYSQL_URL}:3306/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
>>>>>>> 961b6a6af95d063e3794740e2a6047b0f7b0cbb3
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      hibernate.jdbc.batch_size: 20
    show-sql: true
  output:
    ansi:
      enabled: always
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
    '[come.example.inuphonebook]': DEBUG
    '[org.hibernate.type]': TRACE

location:
  url : "https://"
  url2 : ".inu.ac.kr/user/indexSub.do?codyMenuSeq"
  url2_WWW : "www.inu.ac.kr/user/indexSub.do?codyMenuSeq"
  url_design : ".inu.ac.kr/bbs/board.php?bo_table=bbs_01_01"
  url_sports : ".inu.ac.kr/bbs/board.php?bo_table=sub1_2_a"