server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/inu_phonebook?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true

    username: root
  jpa:
#    hibernate:
#      ddl-auto: create
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      hibernate.jdbc.batch_size: 20
    show-sql: true
  output:
    ansi:
      enabled: always
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  level:
    '[com.example.inuphonebook]': DEBUG
    '[org.hibernate.type]': TRACE

location:
  url : "https://"
  url2 : ".inu.ac.kr/user/indexSub.do?codyMenuSeq"
  url2_WWW : "www.inu.ac.kr/user/indexSub.do?codyMenuSeq"
  url_design : ".inu.ac.kr/bbs/board.php?bo_table=bbs_01_01"
  url_sports : ".inu.ac.kr/bbs/board.php?bo_table=sub1_2_a"